### PR TITLE
Feature/juno pipeline show prep

### PR DESCRIPTION
**Pull request by skeleturtle**
Hey Des,
This was a really quick update on my end for the JunoPipeline plugin. I did run the formatter and linter as well. I'm not sure if the staticMethod update to the @pluginlib.abstractmethod was correct, but I followed what you had for the install function. StaticMethod one,  was going to be an error since it was using self.

- adjusted our DeliveryTemplate task to utilize the new ShowPrep task type.
-  Formatted
-  Ran the linter, and adjusted 1 error. I copied over the install decorator, to our uninstall function. Let me know if this should be a different decorator.
- I left 2 other linter issues, using Ruff to disable the imports not being at the top-level. It caused Ruff to go a little crazy, and start flagging a bunch of other issues it wasn't earlier.

### CODE REVIEW

**Comment by ddesmond** [comment]
looks good!

**Comment by skeleturtle** [comment]
@ddesmond 

I merged but I just realized the @pluginlib.abstractmethod decorator added to the base terra plugins uninstall method probably shouldn't be used, since currently none of our plugins actually utilize this method. Should we even have a decorator for the unistall?

**Comment by ddesmond** [comment]
well you are one step ahead of me now :) we did plan to use the uninstall to be able to remove the plugin once we have its metadata saving.
maybe ask @aldmbmtl how he envoisoned the uninstalling?
I never added that code for the plugins I wrote, so there is another ticket, to update the plugins to be uninstalable.

**Comment by aldmbmtl** [comment]
The metadata is saving now in the cluster, that is how the launcher accesses the install locations with the terra installs. I don't think there is anything blocking adding uninstall? If there is, please let me know so I can add it to Terra :)

**Pull request merged**
